### PR TITLE
Refactor agent task runner

### PR DESCRIPTION
**Pull request by at-wat**
- Refactor agent task runner
  - Control blocking tasks by context
  - Add tests to check deadlock by calling Close/Restart in state change callback
  - Remove unnecessary chan
- Fix deadlock in SelectedCandidatePairChange
  - Call handler in different routine

### CODE REVIEW

**Comment by Sean-Der** [comment]
Wow this is amazing, nice work @at-wat :)

Want me to fix the remaining races/failures?

**Comment by at-wat** [comment]
Fixed a little bit.
Remained error seems to be from pion/turn package https://github.com/pion/ice/issues/216.

**Comment by at-wat** [comment]
OnSelectedCandidatePairChange callback also causes same deadlock.

**Comment by Sean-Der** [comment]
@at-wat just merged other PR! Sorry mind rebasing :(

I will take https://github.com/pion/ice/issues/216, you have done so much work already. I am not happy with that test either, I am going to rewrite it to not be so timing dependent.

I want to allow STUN Timeout to be configured for 30 seconds, and allow the test to run for 30 seconds before failing (and other stuff like that). Right now the window is so small it worries me it will flake.

**Comment by at-wat** [comment]
```
=== RUN   TestRemoteLocalAddr/Remote/Local_Pair_Match_between_Agents
    TestRemoteLocalAddr/Remote/Local_Pair_Match_between_Agents: transport_test.go:458: 
        	Error Trace:	transport_test.go:458
        	Error:      	Not equal: 
        	            	expected: &net.UDPAddr{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x14, 0x0, 0x55}, Port:38709, Zone:""}
        	            	actual  : &net.UDPAddr{IP:net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0xa, 0x14, 0x0, 0x55}, Port:58124, Zone:""}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,3 +4,3 @@
        	            	  },
        	            	- Port: (int) 38709,
        	            	+ Port: (int) 58124,
        	            	  Zone: (string) ""
        	Test:       	TestRemoteLocalAddr/Remote/Local_Pair_Match_between_Agents
```

**Pull request merged**
