### PR TITLE
Use binding request for keepalive

### PR DESCRIPTION
**Pull request by hugoArregui**
instead of indication (to support consent refreshness)

### CODE REVIEW

**Comment by notedit** [comment]
It works,  thanks.

**Comment by notedit** [comment]
@Sean-Der  Will we merge this?

**Comment by notedit** [comment]
@hugoArregui will we finish this?

**Comment by hugoArregui** [comment]
@notedit sorry about the delay, I tested the scenario I was worried about but it's working fine

**Comment by Sean-Der** [comment]
nice, thank you for fixing this @hugoArregui :)

**Pull request merged**
