### PR TITLE
Remove nominationRequestCount

### PR DESCRIPTION
**Pull request by Sean-Der**
Before then nominating a candidate pair we limited the
amount of requests we sent, and would set the connection
to failed.

This change removes that limit, and instead uses the Disconnected+Failed
timer to control this. I found this when debugging an unrelated thing,
and was suprised by the behavior. I didn't find anything in the spec
that mentioned this, and isn't a knob that users will understand how to
control easily.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@hugoArregui I recently added the `Failed` state to match WebRTC in the browser, and also added `ICE Restarts`.

Going to failed exists outside `selection.go` now, and is consistent across different agent types. If yo are in checking for Disconnected+Failed time it gives up (30 seconds)

I think with everything else we added this change isn't needed anymore? We correctly go to fail, and I think it is ok to sit in checking for a while on this?

**Comment by Sean-Der** [comment]
@at-wat do you mind if I tag `v2.0.0` for `pion/webrtc` ? Or should we investigate any more issues?

**Comment by at-wat** [comment]
@Sean-Der I think it's better to add a parameter for https://github.com/pion/ice/pull/201.
Or we can tag `-rc` until the API gets stable as we did at pion/dtls.

**Comment by hugoArregui** [comment]
> @hugoArregui I recently added the `Failed` state to match WebRTC in the browser, and also added `ICE Restarts`.

I think this is ok, I thought this was part of the standard but I cannot find it so I'm probably confusing it with something else.

**Pull request merged**
