### PR TITLE
gather all candidate types in parallel

### PR DESCRIPTION
**Pull request by nerd2**
This was an especially noticable issue in an environment where all UDP
was blocked, then we waited for STUN to timeout (5 seconds) before trying
TCP/turn

### CODE REVIEW

**Comment by Sean-Der** [comment]
:fire: nice fix! Would love to merge this right away :)

Would a small test be possible? Maybe do a bunch of invalid STUN servers, and then one TURN server?

**Comment by nerd2** [comment]
>  nice fix! Would love to merge this right away :)
> 
> Would a small test be possible? Maybe do a bunch of invalid STUN servers, and then one TURN server? If you don't have the time I can do this and will get it merged tonight :)

I hope this is ok?

**Comment by nerd2** [comment]
I don't _think_ I introduced the timeout in the test failure.... any help appreciated

**Comment by at-wat** [comment]
I think this timeout error is not related to this PR. https://github.com/pion/ice/issues/204#issuecomment-650548441
I restarted the CI job.

**Comment by Sean-Der** [comment]
Merged, thank you so much for the contribution @nerd2 :)

Would you be interested in joining the Pion organization? No obligations, but I would love to have you involved in the development! It is all individual contributors, so would really love to have you continue making these deep proactive changes.

After that you only need one approver to get your commit merged, and you can approve other peoples commits. So you can work on anything you think is important. The developers drive the roadmap, so you don't need to worry about business pressures.

Also community wise we use GitHub and [Slack](https://pion.ly/slack). I am there all the time, and happy to answer questions any time.

**Pull request merged**
