### PR TITLE
Remove global state for ICE TCP

### LINKED ISSUE #253: Remove global state for ICE TCP
Relates to #245.

### PR DESCRIPTION
**Pull request by jeremija**
This addresses a few points issue of #245:

 - Take a `net.Listener` instead of having global state
 - <strike>Expose a `net.PacketConn` based API, Agent</strike> Expose a `net.TCPMux` based API

Also, the unused `CloseChannel` was removed from `tcp_mux.go`.

Closes #253.

### CODE REVIEW

**Comment by jeremija** [comment]
@Sean-Der I know we talked about how we should avoid `nil` values, but I couldn't figure out of a better solution now that `TCPMux` is optional. I'd be happy to hear if you have a solution that allows to never have a `nil` value here.

**Comment by Sean-Der** [comment]
Absolutely amazing, this is so exciting to see a red diff :) couple ideas/points (push back if you disagree)

* I would make `TCPMux` an interface. That way we can mock it out in the future if we need.
* Maybe do a `invalidTCPMux` instead of a nil pointer?  Just so much easier to be resilient when stuff returns an err (instead of segv the whole process)

**Comment by jeremija** [comment]
Sounds good, will try to do it over the weekend! An alternative would be to make the pointer receiver methods check whether the pointer is nil, but I like your solution better.

**Comment by jeremija** [comment]
I think we will probably need a method that would allow us to close a TCP connection eventually. Something like:

```go
func (t *TCPMux) CloseConn(ufrag string, raddr net.Addr)
```

WDYT?

**Comment by Sean-Der** [comment]
This is something a user will need to do?

Right now every gathered candidate gets closed internally, so `ufrag`s shouldn't pile up? (I think)

sorry will check on my laptop soon :)

**Comment by jeremija** [comment]
No worries, I think I'm just getting a little confused :) So when I look at this statement from https://tools.ietf.org/html/rfc6544: 

> When ICE processing for a media stream completes, each agent SHOULD close all TCP connections (that were opened due to this ICE session) except the ones between the candidate pairs selected by ICE.

In the context of our host (listening tcp) candidate, this doesn't mean we have to manually close the remote TCP connections? Is this because these (potentially unselected) inbound TCP connections will actually be handled (closed) internally as remote candidates?

**Comment by jeremija** [comment]
I have addressed both of your points:

> - [x] I would make TCPMux an interface. That way we can mock it out in the future if we need.
> - [x] Maybe do a invalidTCPMux instead of a nil pointer? Just so much easier to be resilient when stuff returns an err (instead of segv the whole process)

and I'm going to merge this since you already approved it. If you have any concerns about I'd be push and fix later. I'll tag this release and push an update to `pion/webrtc`. Excited to finally releasing this feature :)

**Pull request merged**
