### PR TITLE
Single port mode (take 2)

### PR DESCRIPTION
**Pull request by davidzhao**
#### Description

Taking inspiration from @sahdman's original PR and basing it off of TCPMux, here's a take at muxing UDP on a single port.

### CODE REVIEW

**Comment by davidzhao** [comment]
tests seem to be failing for WASM, I'm not too familiar with the error, but it doesn't make a lot of sense to use UDP in wasm environments.

**Comment by Sean-Der** [comment]
@davidzhao really amazing work! I would just disable those tests for WASM, not much value.  We just have it enabled everywhere to make things easier.

If you can fix the lint errors I am 100% with merging this (and then we can go back and optimize things). Since this isn't in the default code path I see no risk.

**Comment by davidzhao** [comment]
@Sean-Der I fixed the lint/test issues that I can. Lemme know if it's good to go.

I'll work on a PR for webrtc next.

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
Approved, really amazing work @davidzhao

It looks like you have one last  `golangci-lint` when that goes green you will be able to `Rebase and merge`

Feel free after that to do `git tag v2.1.0 && git push --tags` and then you can start on `pion/webrtc` PR! That should be super easy, so excited to have you announce this :)

**Comment by davidzhao** [comment]
> It looks like you have one last `golangci-lint` when that goes green you will be able to `Rebase and merge`

Hey Sean, I'm not too sure about this one, it's complaining about the byte slice, which seems efficient enough to pass around. 

What's your suggestion here? convert them to *[]byte or pass *byte.Buffer?

**Pull request merged**
