### PR TITLE
feat: semantic release support

### PR DESCRIPTION
**Pull request by hugoArregui**
semantic release support

### CODE REVIEW

**Comment by Sean-Der** [comment]
LGTM! I am totally up for changing to semantic versioning.

https://www.npmjs.com/package/commitplease looks like what angularjs uses. Looking through their PRs people constantly spam them with commits breaking their rules:)

**Comment by hugoArregui** [comment]
@Sean-Der yes, but it requires node :disappointed: not sure if we should install node just for that (I have no strong opinion on the matter,)

**Comment by Sean-Der** [comment]
> @Sean-Der yes, but it requires node 😞 not sure if we should install node just for that (I have no strong opinion on the matter,)

Agree. Would rather stickto Go (or just shell script!) it looks like the rules are a little more complicated than the checks we have now though.

I am happy as long as subject/body are split up and we have a length limit. This will be really great for generating a changelog, nice work!

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

**Comment by hugoArregui** [comment]
@Sean-Der body is optional though, is that ok?

**Comment by hugoArregui** [comment]
I stil need to test the release script but I need to do it in master directly, if you are ok with everything can you approve @Sean-Der ?

**Comment by Sean-Der** [comment]
@hugoArregui LGTM! When I get a chance I will improve the checks (assert empty lines and check line lengths)

**Pull request merged**
