### PR TITLE
Fix close delay collecting STUN candidates

### PR DESCRIPTION
**Pull request by kylecarbs**
This was causing a 5s delay when closing the agent.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@kylecarbs LGTM! Mind suppressing/fixing the lint errors?

**Comment by kylecarbs** [comment]
@Sean-Der ahh my bad, yes I will fix!

**Comment by kylecarbs** [comment]
@Sean-Der I added a `nolint` for gocognit on `gatherCandidatesSrflx`. I don't believe it truly adds significant cognitive overhead to parse.

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
nice! @kylecarbs really appreciate you getting into the guts/optimizing like this.

**Comment by Sean-Der** [comment]
Tagged `v2.2.4`

**Pull request merged**
