### PR TITLE
Agent.ResetPair() func instead connection timeout

### PR DESCRIPTION
**Pull request by petkunand**
#### Description
force reconnect

### CODE REVIEW

**Comment by Sean-Der** [comment]
Thanks for the contribution @petkunand 

For this functionality we need to implement ICE Restarts. ICE doesn't allow changing the selected pair otherwise. The RFC is [here](https://tools.ietf.org/html/rfc8445#section-9)

**Comment by petkunand** [comment]
@Sean-Der 
ICE Restart possible if place to pion/webrtc/peerconnection.go this code:

// ResetPair connection
func (pc *PeerConnection) ResetPair() {
	if pc.iceGatherer != nil && pc.iceGatherer.agent != nil {
		pc.iceGatherer.agent.ResetPair()
	}
}

it worked in one of my projects

**Comment by Sean-Der** [comment]
Interesting! I have no idea how/why this is working (but will investigate)

Is Pion the offer or answerer? It sounds like Google's ICE stack just allows multiple nominations/selections? 

Even if it does work we need to be careful, Google can change things at anytime and could break Pion. So we have to always make sure to be spec compliant/not program against their bugs.

**Comment by petkunand** [comment]
pion offer

**Pull request closed without merging**
